### PR TITLE
Loading ChatWindow in parallel to Client and LocalDB

### LINKED ISSUE #26: Delay user list and chat loading during application startup
Because the application accesses the server and the local database during its startup, the delay that passes until the UI is visible is rather large.

This can be addressed by either loading the data after the UI initialization or by making the loading process asynchronous. The only exception to this is the authentication process, which consists of acquiring a user ID from the server.

### PR DESCRIPTION
**Pull request by CyB3RC0nN0R**
Fixes #26

### CODE REVIEW

File: src/main/java/envoy/client/ui/ChatWindow.java [hunk 1]
```diff
@@ -334,4 +325,27 @@ private void updateUserStates() {
 	 * Marks messages in the current chat as {@code READ}.
 	 */
 	private void readCurrentChat() { if (currentChat != null) { localDB.setMessagesToRead(currentChat); } }
+
+	/**
+	 * Sets the {@link Client} used by this {@link ChatWindow}. If the client is
+	 * online, the sync thread is started.
+	 *
+	 * @param client the {@link Client} used to send and receive messages
+	 */
```
Comment (delvh) [inline src/main/java/envoy/client/ui/ChatWindow.java]: - [ ] Please add `@since...`

File: src/main/java/envoy/client/ui/ChatWindow.java [hunk 2]
```diff
@@ -334,4 +325,27 @@ private void updateUserStates() {
...
+		this.client = client;
+		if (client.isOnline() && localDB != null) startSyncThread(Config.getInstance().getSyncTimeout());
+	}
+
+	/**
+	 * Sets the {@link LocalDB} used by this {@link ChatWindow}. After invoking this
+	 * method, users and chats will be loaded from the database into the GUI.
+	 *
+	 * @param localDB the {@link LocalDB} used to manage stored messages and users
+	 */
```
Comment (delvh) [inline src/main/java/envoy/client/ui/ChatWindow.java]: - [ ] Please add `@since...`
