### PR TITLE
Fixed postButton - bug and improved logging

### LINKED ISSUE #139: Post button disabled after the first char is typed
**Describe the bug**
When writing a message, sending it (by pressing the post button or the key combination) is only possible after the second character of the message is typed.

**To Reproduce**
1. Open the client and select a contact
2. Enter a single character into the message text field
3. Look at the post button

**Expected behavior**
The button becomes enabled and the message can be sent.

**Screenshots**
grafik

**Additional context**
This probably relates to the recent changes in the key press handling inside `ChatScene`.

### PR DESCRIPTION
**Pull request by delvh**
Fixes #139.
Additionally added enhanced logging capabilities to ease debugging/ troubleshooting.

### CODE REVIEW

File: src/main/java/envoy/client/ui/controller/ChatScene.java [hunk 1]
```diff
@@ -204,6 +197,34 @@ private void addContactButtonClicked() {
...
+	}
+
+	/**
+	 * @param e the keys that have been pressed
+	 * @since Envoy Client v0.1-beta
+	 */
+	@FXML
+	private void checkPostConditions(KeyEvent e) {
+		if (!postButton.isDisabled() && settings.isEnterToSend() && e.getCode() == KeyCode.ENTER
+				|| !settings.isEnterToSend() && e.getCode() == KeyCode.ENTER && e.isControlDown())
```
Comment (CyB3RC0nN0R) [inline src/main/java/envoy/client/ui/controller/ChatScene.java:223]: Not entirely sure about that one, but I think the second arm of the condition bypasses the `!postButton.isDisabled()` check, making the `Ctrl + Enter` combination work regardless of the post button's state. Consider testing my suggestion before merging it.

```suggestion
		if (!postButton.isDisabled() && (settings.isEnterToSend() && e.getCode() == KeyCode.ENTER
				|| !settings.isEnterToSend() && e.getCode() == KeyCode.ENTER && e.isControlDown()))
```

File: src/main/java/envoy/client/ui/controller/ChatScene.java [hunk 2]
```diff
@@ -248,10 +261,12 @@ private void checkKeyCombination(KeyEvent e) {
 	 */
 	@FXML
 	private void postMessage() {
+		final var text = messageTextArea.getText().strip();
+		if (text.isBlank()) throw new IllegalArgumentException("A message without visible text can not be sent.");
```
Comment (CyB3RC0nN0R) [inline src/main/java/envoy/client/ui/controller/ChatScene.java:265]: I think that this condition is unnecessary, because in the `checkPostConditions` methods the following statement is executed:
`postButton.setDisable(messageTextArea.getText().isBlank() || currentChat == null);`

As I've already wrote in my review of that method, this has to be thoroughly tested to make sure no more edge cases are present.

File: src/main/java/envoy/client/ui/controller/ChatScene.java [hunk 3]
```diff
@@ -204,6 +197,34 @@ private void addContactButtonClicked() {
...
+	/**
+	 * @param e the keys that have been pressed
+	 * @since Envoy Client v0.1-beta
+	 */
+	@FXML
+	private void checkPostConditions(KeyEvent e) {
+		if (!postButton.isDisabled() && settings.isEnterToSend() && e.getCode() == KeyCode.ENTER
+				|| !settings.isEnterToSend() && e.getCode() == KeyCode.ENTER && e.isControlDown())
+			postMessage();
+		postButton.setDisable(messageTextArea.getText().isBlank() || currentChat == null);
```
Comment (CyB3RC0nN0R) [inline src/main/java/envoy/client/ui/controller/ChatScene.java:225]: Consider moving this to the top of the method. I am not sure how this will affect the behavior of the method, but it seems to make much more sense to first check whether the post button should even be enabled and only then check the conditions for actually posting the message.

File: src/main/java/envoy/client/ui/controller/ChatScene.java (hunk 1 above)
Comment (delvh) [reply src/main/java/envoy/client/ui/controller/ChatScene.java:223]: You're right. I just tested it. Thank god did I already implement a fail-safe in the postMessage method.

File: src/main/java/envoy/client/ui/controller/ChatScene.java (hunk 3 above)
Comment (delvh) [reply src/main/java/envoy/client/ui/controller/ChatScene.java:225]: I can foresee problems because of keyPressed/ keyReleased.

I just tested it out, and indeed suddenly I could send empty messages via ctrl + enter.
Hence this will not be done.

File: src/main/java/envoy/client/ui/controller/ChatScene.java (hunk 2 above)
Comment (delvh) [reply src/main/java/envoy/client/ui/controller/ChatScene.java:265]: At least for programming purposes it is not.

While I agree, in production it may be unnecessary, while we are still developing Envoy, we will need this small check. I have no interest in resetting my database because of a programming error at another location. Even while trying your little suggestions, I would have send ~5 empty messages without it.
And after all, there is a slight security concern, as some people might otherwise be able to break our program without it ("The user is always guilty" -> even if you try to resolve all possible error sources, you might still oversee something, and you don't want our program to break (on both client and server side) because one key function did not perform a check).

**Comment by CyB3RC0nN0R** [comment]
> 
> 
> Most of my questions have been addressed, thank you for that :)
> 
> Would you mind removing the problematic logger statement in `Startup` or moving it down below the config initialization (I've marked the conversation as unresolved)?

Never mind, I did not see the second commit until I posted the review.

**Comment by delvh** [comment]
> > Most of my questions have been addressed, thank you for that :)
> > Would you mind removing the problematic logger statement in `Startup` or moving it down below the config initialization (I've marked the conversation as unresolved)?
> 
> Never mind, I did not see the second commit until I posted the review.

I needed to do that is I cannot refactor inside GitHub, hence I needed Eclipse.

**Comment by delvh** [comment]
Wait a second...
I just noticed that you did NOT change my title.
That must be a first!
Wonders can happen!

**Comment by CyB3RC0nN0R** [comment]
> 
> 
> Wait a second...
> I just noticed that you did NOT change my title.
> Neither was the description nor anything else changed.
> That must be a first!
> Wonders can happen!
> Are you sick?

I guess the wonders of correct grammar and orthography have finally entered the realms of our glorious project ;)

File: src/main/java/envoy/client/ui/Startup.java [hunk 4]
```diff
@@ -73,24 +75,24 @@ public void start(Stage stage) throws Exception {
 		EnvoyLog.setFileLevelBarrier(config.getFileLevelBarrier());
 		EnvoyLog.setConsoleLevelBarrier(config.getConsoleLevelBarrier());
 
+		logger.log(Level.INFO, "Envoy was started at " + new Date());
```
Comment (CyB3RC0nN0R) [inline src/main/java/envoy/client/ui/Startup.java:78]: So, I've recently pulled these changes to try them out and noticed the following: `[2020-06-19 08:26:14] [INFO   ] [envoy.client.ui.Startup] Envoy was started at Fri Jun 19 08:26:14 CEST 2020`. Seems pretty redundant to me, so lets shorten that a bit.

Also, I think the suggested wording depicts the situation a bit clearer because the startup process is not actually completed at the time the log record is published.

```suggestion
		logger.log(Level.INFO, "Envoy starting...";
```

File: src/main/java/envoy/client/net/Receiver.java [hunk 5]
```diff
@@ -54,29 +54,30 @@ public void run() {
...
+						logger.log(Level.WARNING, String.format(
+							"The received object has the class %s for which no processor is defined.", obj.getClass()));
 					else processor.accept(obj);
 				}
 			}
-		} catch (SocketException e) {
+		} catch (final SocketException e) {
 			// Connection probably closed by client.
-		} catch (Exception e) {
+		} catch (final Exception e) {
```
Comment (DieGurke) [inline src/main/java/envoy/client/net/Receiver.java:80]: Whats the reason for all of them being final now?

File: src/main/java/envoy/client/ui/Startup.java [hunk 6]
```diff
@@ -103,20 +105,21 @@ public void start(Stage stage) throws Exception {
...
 		try {
-			logger.info("Closing connection...");
+			logger.log(Level.INFO, "Closing connection...");
 			client.close();
 
-			logger.info("Saving local database and settings...");
+			logger.log(Level.INFO, "Saving local database and settings...");
 			localDB.save();
 			Settings.getInstance().save();
+			logger.log(Level.INFO, "Envoy was stopped as expected at " + new Date());
```
Comment (DieGurke) [inline src/main/java/envoy/client/ui/Startup.java:120]:
```suggestion
			logger.log(Level.INFO, "Envoy was terminated as expected at " + new Date());
```

File: src/main/java/envoy/client/ui/controller/ChatScene.java [hunk 7]
```diff
@@ -276,12 +292,13 @@ private void postMessage() {
 			if (!localDB.getIDGenerator().hasNext() && client.isOnline()) client.requestIdGenerator();
 
 		} catch (final IOException e) {
-			logger.log(Level.SEVERE, "Error sending message", e);
+			logger.log(Level.SEVERE, "Error sending message: ", e);
```
Comment (DieGurke) [inline src/main/java/envoy/client/ui/controller/ChatScene.java:295]:
```suggestion
			logger.log(Level.SEVERE, "Error at sending message: ", e);
```

File: src/main/java/envoy/client/net/Receiver.java (hunk 5 above)
Comment (delvh) [reply src/main/java/envoy/client/net/Receiver.java:80]: My formatter.

File: src/main/java/envoy/client/ui/controller/ChatScene.java (hunk 7 above)
Comment (delvh) [reply src/main/java/envoy/client/ui/controller/ChatScene.java:295]:
```suggestion
			logger.log(Level.SEVERE, "Error while sending message: ", e);
```

File: src/main/java/envoy/client/ui/Startup.java (hunk 6 above)
Comment (delvh) [reply src/main/java/envoy/client/ui/Startup.java:120]:
```suggestion
			logger.log(Level.INFO, "Envoy was terminated by its user;
```

File: src/main/java/envoy/client/ui/controller/ChatScene.java [hunk 8]
```diff
@@ -292,7 +292,7 @@ private void postMessage() {
 			if (!localDB.getIDGenerator().hasNext() && client.isOnline()) client.requestIdGenerator();
 
 		} catch (final IOException e) {
-			logger.log(Level.SEVERE, "Error sending message: ", e);
+			logger.log(Level.SEVERE, "Error while sending message: ", e);
```
Comment (CyB3RC0nN0R) [inline src/main/java/envoy/client/ui/controller/ChatScene.java:295]: Thought so.

**Comment by delvh** [comment]
Can I merge?

**Comment by CyB3RC0nN0R** [comment]
> Can I merge?

Yes, I think so.
