### PR TITLE
Silent failure when StatusTrayIcon is not supported on a platform

### LINKED ISSUE #46: StatusTrayIcon does not work on Linux
one solution would be to throw an error if not supported and only allow otherwise.

### PR DESCRIPTION
**Pull request by CyB3RC0nN0R**
Fixes #46

### CODE REVIEW

File: src/main/java/envoy/client/ui/Startup.java [hunk 1]
```diff
@@ -71,12 +71,17 @@ public static void main(String[] args) {
 					JOptionPane.WARNING_MESSAGE);
 		}
 		Settings.getInstance().setUsername(userName);
-		
+
 		EventQueue.invokeLater(() -> {
 			try {
 				ChatWindow chatWindow = new ChatWindow(client, localDB);
-				new StatusTrayIcon(chatWindow).show();
```
Comment (CyB3RC0nN0R) [inline src/main/java/envoy/client/ui/Startup.java]: I have additionally moves the initialization of the status tray icon below the part where the chat window is made visible to prevent any delays caused by it.
