### PR TITLE
Added and fixed existing Javadoc, configured Javadoc validation

### LINKED ISSUE #59: Documentation
Every type and their public members should be fully documented with Javadoc.

### PR DESCRIPTION
**Pull request by CyB3RC0nN0R**
I have tried to catch all of the small Javadoc errors, but may have missed some. If you notice any misspelling or other mistake, feel free to point it out in the review.

Fixes #59

### CODE REVIEW

File: src/main/java/envoy/client/Config.java [hunk 1]
```diff
@@ -24,6 +29,9 @@
 
 	private Config() {}
 
+	/**
+	 * @return the singleton instance of the {@link Config}
+	 */
```
Comment (delvh) [inline src/main/java/envoy/client/Config.java]: - [ ] Please add `@since Envoy v0.1-alpha`

File: src/main/java/envoy/client/event/MessageEvent.java [hunk 2]
```diff
@@ -13,6 +13,12 @@
 
 	protected final Message message;
 
+	/**
+	 * Initializes a {@link MessageEvent} conveying information about a
+	 * {@link Message} object.
+	 *
+	 * @param message the {@link Message} object to attach to this event
+	 */
```
Comment (delvh) [inline src/main/java/envoy/client/event/MessageEvent.java]: - [ ] Please add `@since Envoy v0.2-alpha`

File: src/main/java/envoy/client/event/ThemeChangeEvent.java [hunk 3]
```diff
@@ -13,6 +13,12 @@
 
 	private final Theme theme;
 
+	/**
+	 * Initializes a {@link ThemeChangeEvent} conveying information about the change
+	 * of the {@link Theme} currently in use
+	 *
+	 * @param theme the new currently used {@link Theme} object
+	 */
```
Comment (delvh) [inline src/main/java/envoy/client/event/ThemeChangeEvent.java]: - [ ] Please add `@since Envoy v0.2-alpha`

File: src/main/java/envoy/client/ui/ChatWindow.java [hunk 4]
```diff
@@ -66,6 +66,13 @@
 
 	private static final Logger logger = EnvoyLog.getLogger(ChatWindow.class.getSimpleName());
 
+	/**
+	 * Initializes a {@link JFrame} with UI elements used to send and read messages
+	 * to different users.
+	 *
+	 * @param client  the {@link Client} used to send and receive messages
+	 * @param localDB the {@link LocalDB} used to manage stored messages and users
+	 */
```
Comment (delvh) [inline src/main/java/envoy/client/ui/ChatWindow.java]: - [ ] Please add `@since Envoy v0.1-alpha`

File: src/main/java/envoy/client/ui/Startup.java [hunk 5]
```diff
@@ -32,6 +32,16 @@
...
+	/**
+	 * Loads the application by first loading the configuration, then acquiring a
+	 * user name and connecting to the server. If the server cannot be reached,
+	 * offline mode is entered if possible. After that, a {@link ChatWindow}
+	 * instance is initialized and then displayed to the user. Upon application
+	 * exit, settings and the local database are saved.
+	 *
+	 * @param args the command line arguments may contain configuration parameters
+	 *             and are parsed by the {@link Config} class
+	 */
```
Comment (delvh) [inline src/main/java/envoy/client/ui/Startup.java]: - [ ] Please add `@since Envoy v0.1-alpha`

File: src/main/java/envoy/client/ui/Theme.java [hunk 6]
```diff
@@ -26,6 +26,22 @@
...
+	 * @param interactableForegroundColor the color of interactable foreground UI
+	 *                                    elements
+	 * @param interactableBackgroundColor the color of interactable background UI
+	 *                                    elements
+	 * @param messageColorChat            the color of chat messages
+	 * @param dateColorChat               the color of chat message metadata
+	 * @param selectionColor              the section color
+	 * @param typingMessageColor          the color of currently typed messages
+	 * @param userNameColor               the color of user names
+	 */
```
Comment (delvh) [inline src/main/java/envoy/client/ui/Theme.java]: - [ ] Please add `@since Envoy v0.2-alpha`

File: src/main/java/envoy/client/ui/Theme.java [hunk 7]
```diff
@@ -42,6 +58,13 @@ public Theme(String themeName, Color backgroundColor, Color cellColor, Color int
 		this.userNameColor					= userNameColor;
 	}
 
+	/**
+	 * Initializes a {@link Theme} by copying all parameters except for the name
+	 * from another {@link Theme} instance.
+	 *
+	 * @param name  the name of the {@link Theme}
+	 * @param other the {@link Theme} to copy
+	 */
```
Comment (delvh) [inline src/main/java/envoy/client/ui/Theme.java]: - [ ] Please add `@since Envoy v0.2-alpha`
